"""Ingredient taxonomy and relation keywords used by the NER processor."""

INGREDIENTS: dict[str, list[str]] = {
    "PROTEINA": [
        "camarão",
        "camarões",
        "peixe",
        "frango",
        "carne",
        "filé",
        "lagosta",
        "polvo",
        "lula",
        "porco",
        "bacon",
        "ovo",
        "ovos",
        "salmão",
        "bacalhau",
        "atum",
        "picanha",
        "alcatra",
        "maminha",
        "cordeiro",
        "sertão",
    ],
    "CARBOIDRATO": [
        "arroz",
        "feijão",
        "batata",
        "batatas",
        "macarrão",
        "massa",
        "cuscuz",
        "mandioca",
        "macaxeira",
        "farinha",
        "farofa",
        "espaguete",
        "fettuccine",
        "penne",
        "pão",
        "torrada",
        "batata frita",
        "purê",
    ],
    "VEGETAL": [
        "cebola",
        "alho",
        "tomate",
        "pimentão",
        "cheiro-verde",
        "coentro",
        "salsa",
        "alface",
        "rúcula",
        "agrião",
        "azeitona",
        "palmito",
        "milho",
        "ervilha",
        "brócolis",
        "couve",
        "abóbora",
        "jerimum",
        "berinjela",
        "abobrinha",
        "cogumelo",
        "cogumelos",
    ],
    "LATICINIO": [
        "queijo",
        "queijos",
        "leite",
        "creme de leite",
        "manteiga",
        "requeijão",
        "parmesão",
        "muçarela",
        "mussarela",
        "coalho",
        "catupiry",
        "gorgonzola",
        "provolone",
        "ricota",
    ],
    "TEMPERO_MOLHO": [
        "sal",
        "pimenta",
        "azeite",
        "óleo",
        "limão",
        "vinagre",
        "louro",
        "molho",
        "molho branco",
        "molho de tomate",
        "manjericão",
        "orégano",
        "shoyu",
        "mostarda",
        "ketchup",
        "maionese",
        "curry",
        "cominho",
    ],
}

# The previous "COM" entry (matching any "com"/"e") was dropped: those
# words are ubiquitous in Portuguese descriptions and produced spurious
# edges between every pair of ingredients.
RELATION_KEYWORDS: dict[str, list[str]] = {
    "RECHEADO_COM": ["recheado", "recheada", "recheados", "recheadas"],
    "ACOMPANHADO_DE": [
        "acompanhado",
        "acompanhada",
        "acompanhados",
        "acompanhadas",
        "servido com",
    ],
    "AO_MOLHO_DE": ["ao molho", "com molho"],
}

INGREDIENT_CATEGORY: dict[str, str] = {
    name: category for category, names in INGREDIENTS.items() for name in names
}
